//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlutenFree.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlutenFree.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string LabelDarkSettingsPage {
            get {
                return ResourceManager.GetString("LabelDarkSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LabelLightSettingsPage {
            get {
                return ResourceManager.GetString("LabelLightSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string LabelSystemSettingsPage {
            get {
                return ResourceManager.GetString("LabelSystemSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string LabelThemeSettingsPage {
            get {
                return ResourceManager.GetString("LabelThemeSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a restaurant....
        /// </summary>
        internal static string PlaceholderMap {
            get {
                return ResourceManager.GetString("PlaceholderMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a province....
        /// </summary>
        internal static string PlaceholderProvinces {
            get {
                return ResourceManager.GetString("PlaceholderProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a region....
        /// </summary>
        internal static string PlaceholderRegions {
            get {
                return ResourceManager.GetString("PlaceholderRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No province to show.
        /// </summary>
        internal static string ProvincesNotLoading {
            get {
                return ResourceManager.GetString("ProvincesNotLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No region to show.
        /// </summary>
        internal static string RegionsNotLoading {
            get {
                return ResourceManager.GetString("RegionsNotLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string StringMap {
            get {
                return ResourceManager.GetString("StringMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces.
        /// </summary>
        internal static string StringProvinces {
            get {
                return ResourceManager.GetString("StringProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        internal static string StringRegions {
            get {
                return ResourceManager.GetString("StringRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string StringSettings {
            get {
                return ResourceManager.GetString("StringSettings", resourceCulture);
            }
        }
    }
}
